### ISSUE TITLE
Idea: Media with Model

### ISSUE THREAD

**Issue by findridoy** [FarhanShares/laravel-mediaman#36]
Hey, I didn't explore the code, so if I missed I am sorry but:

Let's say I have some post model and I had associated a image with those model.

So when retrieving the model can I do that?

$myPosts = Post::whereIn('id',[1,2,3,4,5])-with('thereImage')->get();

**Comment by FarhanShares** [comment]
Sure, you can eager load media. However, the relationship name is 'media'.

$myPosts = Post::with('media')->whereIn('id', [1, 2, 3, 4, 5])->get();

Closing the issue, reopen if needed.
